name: pgset
container:
  port: 5432
  name:
    default: pgset
    primary: pgset-primary
    replica: pgset-replica
  serviceAccount: pgset-sa
credentials:
  primary: password
  root: password
  user: password
serviceType: ClusterIP
image:
  repository: crunchydata
  container: crunchy-postgres
  tag: centos7-10.4-1.8.3
pv:
  storage: 400M
  name: pgset-pv
pvc:
  name: pgset-pvc
resources:
  cpu: 200m
  memory: 512Mi
  persistence:
    storageClass: standard
    storageClassType: standard
    accessModes:
    - ReadWriteMany
    size: 100m
