apiVersion: v1
kind: Pod
metadata:
  name: "{{.Values.Container.Name}}"
  labels:
    name: "{{.Values.Container.Name}}"
    # The "heritage" label is used to track which tool deployed a given chart.
    # It is useful for admins who want to see what releases a particular tool
    # is responsible for.
    heritage: {{.Release.Service | quote }}
    # The "release" convention makes it easy to tie a release to all of the
    # Kubernetes resources that were created as part of that release.
    release: {{.Release.Name | quote }}
    # This makes it easy to audit chart usage.
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
    "helm.sh/created": {{.Release.Time.Seconds | quote }}
spec:
  # This shows how to use a simple value. This will look for a passed-in value
  # called restartPolicy. If it is not found, it will use the default value.
  # {{default "Never" .restartPolicy}} is a slightly optimized version of the
  # more conventional syntax: {{.restartPolicy | default "Never"}}
  restartPolicy: {{default "Never" .Values.restartPolicy}}
  containers:
  - name: {{.Values.Container.Name.Primary}}
    image: "{{.Values.Image.Repository}}/{{.Values.Image.Container}}:{{.Values.Image.Tag}}"
    ports:
    - containerPort: 5432
    env:
    - name: PGHOST
      value: /tmp
    - name: PG_PRIMARY_USER
      value: primaryuser
    - name: PG_MODE
      value: primary
    - name: PG_PRIMARY_PORT
      value: "5432"
    - name: PG_PRIMARY_PASSWORD
      value: "{{.Values.Credentials.Primary}}"
    - name: PG_USER
      value: testuser
    - name: PG_PASSWORD
      value: "{{.Values.Credentials.User}}"
    - name: PG_DATABASE
      value: userdb
    - name: PG_ROOT_PASSWORD
      value: "{{.Values.Credentials.Root}}"
    volumeMounts:
    - mountPath: /pgdata
      name: pgdata
    - mountPath: /backup
      name: backup
      readOnly: true
    - mountPath: /pguser
      name: pguser-volume
      readOnly: true
    - mountPath: /pgprimary
      name: pgprimary-volume
      readOnly: true
    - mountPath: /pgroot
      name: pgroot-volume
      readOnly: true
  volumes:
  - name: pgdata
    persistentVolumeClaim:
     claimName: {{.Values.PVC.Name}}
  - emptyDir: {}
    name: backup
  - name: pguser-volume
    secret:
     secretName: pguser-secret
  - name: pgprimary-volume
    secret:
     secretName: pgprimary-secret
  - name: pgroot-volume
    secret:
     secretName: pgroot-secret
