# Create a primary and async replica from the dockerhub images
# db-replica can be optionally scaled using:
# docker-compose up --scale db-replica=2
---
version: '3'

services:
  db-primary:
    image: crunchydata/crunchy-postgres:centos7-9.6.9-2.0
    ports:
    - "5432"
    volumes:
    - primary:/pgdata
    environment:
    - PGHOST=/tmp
    - MAX_CONNECTIONS=101
    - SHARED_BUFFERS=128MB
    - MAX_WAL_SENDERS=7
    - WORK_MEM=5MB
    - TEMP_BUFFERS=9MB
    - PG_PRIMARY_USER=primaryuser
    - PG_PRIMARY_HOST=db-primary
    - PG_PRIMARY_PASSWORD=password
    - PG_PRIMARY_PORT=5432
    - PG_MODE=primary
    - PG_USER=testuser
    - PG_PASSWORD=password
    - PG_ROOT_PASSWORD=password
    - PG_DATABASE=userdb
  db-replica:
    image: crunchydata/crunchy-postgres:centos7-9.6.9-2.0
    ports:
    - "5432"
    volumes:
    - replica:/pgdata
    links:
    - db-primary
    environment:
    - PGHOST=/tmp
    - MAX_CONNECTIONS=101
    - SHARED_BUFFERS=128MB
    - MAX_WAL_SENDERS=7
    - WORK_MEM=5MB
    - TEMP_BUFFERS=9MB
    - PG_PRIMARY_USER=primaryuser
    - PG_PRIMARY_HOST=db-primary
    - PG_PRIMARY_PORT=5432
    - PG_PRIMARY_PASSWORD=password
    - PG_MODE=replica
    - PG_USER=testuser
    - PG_PASSWORD=password
    - PG_ROOT_PASSWORD=password
    - PG_DATABASE=userdb

volumes:
  primary:
  replica:
