---
global:
  scrape_interval: SCRAPE_INTERVAL
  scrape_timeout: SCRAPE_TIMEOUT
  evaluation_interval: 5s

scrape_configs:
- job_name: 'crunchy-collect'
  kubernetes_sd_configs:
  - role: pod

  relabel_configs:
  - source_labels: [__meta_kubernetes_pod_label_crunchy_collect]
    action: keep
    regex: true
  - source_labels: [__meta_kubernetes_pod_container_port_number]
    action: drop 
    regex: 5432
  - action: labelmap
    regex: __meta_kubernetes_pod_label_(.+)
  - source_labels: [__meta_kubernetes_namespace]
    action: replace
    target_label: kubernetes_namespace
  - source_labels: [__meta_kubernetes_pod_name]
    action: replace
    target_label: kubernetes_pod_name
  - source_labels: [__meta_kubernetes_pod_name]
    action: replace
    target_label: instance
